image: maven:3.9-eclipse-temurin-23

stages:
  - validate
  - test
  - package
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  WEKA_VERSION: "3-8-6"
  WEKA_JAR_PATH: "/opt/weka/weka.jar"

before_script:
  - apt-get update && apt-get install -y wget unzip
  - mkdir -p /opt/weka
  - wget -q https://prdownloads.sourceforge.net/weka/weka-${WEKA_VERSION}.zip -O weka.zip
  - unzip -q weka.zip -d /opt/weka
  - export CLASSPATH=$WEKA_JAR_PATH:$CLASSPATH


validate-project:
  stage: validate
  script:
    - 'mvn $MAVEN_CLI_OPTS compile'
  artifacts:
    paths:
      - target
    expire_in: 30 minutes

run-unit-tests:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS -Dmaven.main.skip=true test'

build-dist:
  stage: package
  script:
    - 'mvn $MAVEN_CLI_OPTS -Dmaven.main.skip=true -Dmaven.test.skip=true package'
  artifacts:
    paths:
      - target/*.jar

deploy-to-test-server:
  stage: deploy
  script:
    - 'true'
    
deploy-to-production:
  stage: deploy
  script:
    - 'true'
  only:
    - master
